# Generated by Django 3.0.8 on 2020-07-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_nome', models.CharField(max_length=100, unique=True, verbose_name='PlayList')),
                ('playlist_canal', models.CharField(max_length=100, verbose_name='Canal')),
                ('playlist_idioma', models.CharField(choices=[('Português', 'Português'), ('Inglês', 'Inglês'), ('Espanhol', 'Espanhol'), ('Italiano', 'Italiano'), ('Francês', 'Francês'), ('Alemão', 'Alemão')], default='pt', max_length=30, verbose_name='Idioma')),
                ('playlist_numero_v', models.CharField(blank=True, max_length=4, verbose_name='Número de Vídeos')),
                ('playlist_url', models.URLField(max_length=300, verbose_name='Link')),
                ('playlist_foto', models.ImageField(upload_to='playlist_img')),
                ('playlist_categoria', models.ManyToManyField(to='base.Categoria')),
            ],
            options={
                'verbose_name': 'PlayList',
                'verbose_name_plural': 'PlayLists',
                'ordering': ['playlist_nome'],
            },
        ),
    ]
