# Generated by Django 3.0.8 on 2020-08-01 19:58

from django.db import migrations, models
import playlists.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200720_1450'),
        ('playlists', '0002_playlist_playlist_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_dia',
            field=models.ManyToManyField(blank=True, to='base.DiaTransmissao'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_hora',
            field=models.ManyToManyField(blank=True, to='base.HoraTransmissao'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_observacoes',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_canal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_foto',
            field=models.ImageField(upload_to=playlists.models.upload_to),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_idioma',
            field=models.CharField(choices=[('Português', 'Português'), ('Inglês', 'Inglês'), ('Espanhol', 'Espanhol'), ('Italiano', 'Italiano'), ('Francês', 'Francês'), ('Alemão', 'Alemão')], default='Português', max_length=30, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_nome',
            field=models.CharField(max_length=100, verbose_name='PlayList'),
        ),
    ]
