# Generated by Django 3.0.8 on 2020-07-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_nome', models.CharField(max_length=23, verbose_name='Canal')),
                ('canal_subtitulo', models.CharField(blank=True, max_length=50, verbose_name='Subtitulo')),
                ('canal_idioma', models.CharField(choices=[('Português', 'Português'), ('Inglês', 'Inglês'), ('Espanhol', 'Espanhol'), ('Italiano', 'Italiano'), ('Francês', 'Francês'), ('Alemão', 'Alemão')], default='Português', max_length=20, verbose_name='Idioma')),
                ('canal_programas', models.TextField(blank=True, max_length=500, verbose_name='Programas')),
                ('canal_observacoes', models.TextField(blank=True, max_length=1500, verbose_name='Observações')),
                ('canal_url', models.URLField(max_length=300, verbose_name='Link')),
                ('canal_site', models.URLField(blank=True, max_length=300, verbose_name='Site')),
                ('canal_facebook', models.URLField(blank=True, max_length=300, verbose_name='Facebook')),
                ('canal_twitter', models.URLField(blank=True, max_length=300, verbose_name='Twitter')),
                ('canal_instagram', models.URLField(blank=True, max_length=300, verbose_name='Instagram')),
                ('canal_foto', models.ImageField(upload_to='canal_img')),
                ('canal_categoria', models.ManyToManyField(to='base.Categoria')),
                ('canal_dia_trans', models.ManyToManyField(blank=True, to='base.DiaTransmissao')),
                ('canal_hora_trans', models.ManyToManyField(blank=True, to='base.HoraTransmissao')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
                'ordering': ['canal_nome'],
            },
        ),
    ]
