# Generated by Django 3.0.8 on 2020-07-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canais', '0002_canal_canal_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='canal_nome',
            field=models.CharField(max_length=30, verbose_name='Canal'),
        ),
    ]
