# Generated by Django 3.0.8 on 2020-07-20 05:41

import canais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canais', '0003_auto_20200718_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='canal_foto',
            field=models.ImageField(upload_to=canais.models.upload_to),
        ),
    ]
