# Generated by Django 3.0.8 on 2020-07-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nome', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['categoria_nome'],
            },
        ),
        migrations.CreateModel(
            name='DiaTransmissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_transmissao', models.CharField(max_length=50, verbose_name='Dias de Transmissão')),
            ],
            options={
                'verbose_name': 'Dia de transmissão',
                'verbose_name_plural': 'Dias de transmissão',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HoraTransmissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_transmissao', models.CharField(max_length=10, verbose_name='Hora de transmissão')),
            ],
            options={
                'verbose_name': 'Hora de transmissão',
                'verbose_name_plural': 'Horas de transmissão',
                'ordering': ['hora_transmissao'],
            },
        ),
    ]
