# Generated by Django 3.0.8 on 2020-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_categoria_categoria_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria_nome',
            field=models.CharField(max_length=30, verbose_name='Categoria'),
        ),
    ]
